/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;
import modeloqytetet.Qytetet;
import java.util.ArrayList;
import modeloqytetet.MetodoSalirCarcel;
import modeloqytetet.TipoCasilla;
import javax.swing.JOptionPane;

/**
 *
 * @author patchispatch
 */
public class ControladorQytetet extends javax.swing.JFrame {
    
    private Qytetet modeloQytetet;

    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
    }
    
    public void actualizar(Qytetet qytetet) {
        modeloQytetet = qytetet;
        vistaQytetet1.actualizar(qytetet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet1 = new GUIQytetet.VistaQytetet();
        jbSalirCarcelConDado = new javax.swing.JButton();
        jbSalirCarcelPagando = new javax.swing.JButton();
        jbJugar = new javax.swing.JButton();
        jbComprar = new javax.swing.JButton();
        jbAplicarSorpresa = new javax.swing.JButton();
        jbPasarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbSalirCarcelConDado.setText("Salir cárcel con dado");
        jbSalirCarcelConDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirCarcelConDadoActionPerformed(evt);
            }
        });

        jbSalirCarcelPagando.setText("Salir cárcel pagando");
        jbSalirCarcelPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirCarcelPagandoActionPerformed(evt);
            }
        });

        jbJugar.setText("JUGAR");
        jbJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJugarActionPerformed(evt);
            }
        });

        jbComprar.setText("Comprar");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });

        jbAplicarSorpresa.setText("Aplicar sorpresa");
        jbAplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplicarSorpresaActionPerformed(evt);
            }
        });

        jbPasarTurno.setText("Pasar turno");
        jbPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPasarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalirCarcelConDado, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jbSalirCarcelPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAplicarSorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPasarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbSalirCarcelConDado)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalirCarcelPagando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbComprar)
                        .addGap(18, 18, 18)
                        .addComponent(jbAplicarSorpresa)
                        .addGap(18, 18, 18)
                        .addComponent(jbPasarTurno)
                        .addGap(112, 112, 112)
                        .addComponent(jbJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirCarcelConDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirCarcelConDadoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.jbSalirCarcelPagando.setEnabled(false);
        this.jbSalirCarcelConDado.setEnabled(false);

        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jbJugar.setEnabled(true);
        }
        
        else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.jbPasarTurno.setEnabled(true);
        }
        
        this.vistaQytetet1.actualizar(modeloQytetet);
        
        vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbSalirCarcelConDadoActionPerformed

    private void jbJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJugarActionPerformed
        boolean tienePropietario = modeloQytetet.jugar();
        this.jbJugar.setEnabled(false);
        
        if(!tienePropietario && modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE) {
            this.jbComprar.setEnabled(true);
        }
        
        else
            this.jbComprar.setEnabled(false);
        
        if(modeloQytetet.getJugadorActual().getEncarcelado()) {
            this.jbPasarTurno.setEnabled(false);
            this.jbSalirCarcelConDado.setEnabled(true);
            this.jbSalirCarcelPagando.setEnabled(true);
        }
        
        if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA){
            this.jbAplicarSorpresa.setEnabled(true);
        }
        
        this.jbPasarTurno.setEnabled(true);
        
        vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbJugarActionPerformed

    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed
        boolean resultado = modeloQytetet.comprarTituloPropiedad();
        
        if(resultado) {
            JOptionPane.showMessageDialog(this, "Se ha comprado la propiedad.");
            this.jbComprar.setEnabled(false);
        }
        
        else
            JOptionPane.showMessageDialog(this, "No se ha podido comprar la propiedad.");
        
        vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbComprarActionPerformed

    private void jbAplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplicarSorpresaActionPerformed
        boolean resultado = modeloQytetet.aplicarSorpresa();
        
        this.jbComprar.setEnabled(!resultado);
        
        vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbAplicarSorpresaActionPerformed

    private void jbPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPasarTurnoActionPerformed
        modeloQytetet.siguienteJugador();
        this.jbJugar.setEnabled(true);
        habilitarComenzarTurno();
        this.vistaQytetet1.actualizar(modeloQytetet);
        
    }//GEN-LAST:event_jbPasarTurnoActionPerformed

    private void jbSalirCarcelPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirCarcelPagandoActionPerformed
         boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.jbSalirCarcelPagando.setEnabled(false);
        this.jbSalirCarcelConDado.setEnabled(false);

        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jbJugar.setEnabled(true);
        }
        
        else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.jbPasarTurno.setEnabled(true);
        }
        
        this.vistaQytetet1.actualizar(modeloQytetet);
    
        vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbSalirCarcelPagandoActionPerformed

    public void habilitarComenzarTurno(){
        this.jbComprar.setEnabled(false);
        this.jbPasarTurno.setEnabled(false);
        this.jbAplicarSorpresa.setEnabled(false);
        this.jbSalirCarcelConDado.setEnabled(false);
        this.jbSalirCarcelPagando.setEnabled(false);
        
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.jbSalirCarcelPagando.setEnabled(true);
            this.jbPasarTurno.setEnabled(true);
        }
        
        else
            this.jbJugar.setEnabled(true);
 } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ControladorQytetet controladorQytetet= new ControladorQytetet();
        
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres = capturaNombres.obtenerNombres();
        
        Qytetet qytetet = Qytetet.getInstance();
        qytetet.inicializarJuego(nombres);
        
        Dado.createInstance(controladorQytetet);
        
        controladorQytetet.actualizar(qytetet);
        
        controladorQytetet.habilitarComenzarTurno();
        
        

        controladorQytetet.setVisible(true); //Última línea del main
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAplicarSorpresa;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbJugar;
    private javax.swing.JButton jbPasarTurno;
    private javax.swing.JButton jbSalirCarcelConDado;
    private javax.swing.JButton jbSalirCarcelPagando;
    private GUIQytetet.VistaQytetet vistaQytetet1;
    // End of variables declaration//GEN-END:variables
}
